Added full support for VMs

diff --git a/geode-addon-deployment/src/main/resources/bin_sh/vm_copy b/geode-addon-deployment/src/main/resources/bin_sh/vm_copy
--- a/geode-addon-deployment/src/main/resources/bin_sh/vm_copy
+++ b/geode-addon-deployment/src/main/resources/bin_sh/vm_copy
@@ -7,7 +7,7 @@ EXECUTABLE="`basename $0`"
 
 __options()
 {
-   echo "-cluster -vm -key -?"
+   echo "-cluster -vm -simulate -?"
 }
 
 if [ "$OPTIONS" == "true" ]; then
@@ -38,43 +38,46 @@ NAME
                  specified VMs in geode-addon environment
 
 SYNOPSIS
-   $EXECUTABLE [-cluster cluster_name] [-key private_key_file] [-vm comma_separated_hosts] [-mirror] [-?] file_path
+   $EXECUTABLE [-cluster cluster_name] [-vm comma_separated_hosts] [-mirror] [-simulate] [-?] file_path
 
 DESCRIPTION
-   Copies the specified file or directory to the to the specified VMs. The
-   file path can be an absolute or a relative path but it must exist in the
-   workspace directory hiearchy. To copy non-workspace files, specify the 'mirror'
-   option, which copies the file to the exact same path as the local path.
+   Copies the specified file or directory to all the VMs defined by the VM_HOSTS
+   environment variable in the workspace 'setenv.sh' file. To copy to only the
+   cluster VMs, specify the cluster with the '-cluster' option. To copy to a select
+   list of VMs, specify the VM list with the '-vm' option.
 
-   If the file path is a directory then all of the files in the directory
-   are recursively copied.
+   The file path can be an absolute or a relative path but it must exist in the workspace
+   directory hiearchy. To copy non-workspace files, specify the 'mirror' option, which
+   copies the file to the same path as the local path.
 
-   If the '-vm' option is not specified, then it copies the specified file to
-   the hosts defined by the VM_HOSTS environment variable defined in the
-   workspace 'setenv.sh' file.
+   If the file path is a directory then all of the files in the directory are recursively
+   copied.
+
+   Note that this command and all other commands that begin with the "vm_" preprefix are
+   available only on VM workspaces.
+
+   The '-vm' option overrides both the '-cluster' option and VM_HOSTS. The '-cluster' option
+   overrides VM_HOSTS. 
 
 OPTIONS
+   -cluster cluster_name
+             Cluster name.
 
-    -cluster cluster_name
-              Cluster name.
+   -vm comma_separated_hosts
+             A comma separated list of VM hosts or addresses. Spaces NOT allowed.
 
-    -vm comma_separated_hosts
-              A list of VM hosts or addresses separated by comma. Spaces NOT allowed.
+   -mirror
+             If this option is specified, then the absolute path of the specified
+             file is duplicated in the remote VMs such that both local and remote
+             files paths will be identical. If the absolute path does not exist in
+             the remote VMs, then this command will fail.
 
-    -key private_key_file
-              Private key file path. To ssh into your VM such as the ones on AWS, you may
-              supply your private key file. Normally, the private key file is not
-              required if you have set public-key authentication.
+   -simulate
+             Print the remote commands but do not execute.
 
-    -mirror
-              If this option is specified, then the absolute path of the specified
-              file is duplicated in the remote VMs such that both local and remote
-              files paths will be identical. If the absolute path does not exist in
-              the remote VMs, then this command will fail.
-
-    file_path
-              File or directory path. Multiple files not supported. If directory, then
-              the entire directory is recursively copied to all the VMs.
+   file_path
+             File or directory path. Multiple files not supported. If directory, then
+             the entire directory is recursively copied to all the VMs.
 
 EOF
 if [ "$MAN_SPECIFIED" == "false" ]; then
@@ -91,6 +94,60 @@ EOF
    exit
 fi
 
+# Available only on VM workspaces
+if [ "$VM_ENABLED" != "true" ]; then
+   echo "----------------------------------------------------------------"
+   echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+   echo "    ERROR: The workspace is not a VM workspace. Command aborted."
+   echo "----------------------------------------------------------------"
+   exit 1 
+fi
+
+# If the -vm option is specified then it overrides all other options
+if [ "$VM_SPECIFIED" == "true" ]; then
+   if [ "$VM_HOSTS_ARG" != "" ] && [[ "$VM_HOSTS_ARG" != *"-"* ]]; then
+      VM_HOSTS=$VM_HOSTS_ARG
+   else
+      echo "----------------------------------------------------------------"
+      echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+      echo >&2 "ERROR: Invalid value for -vm [$VM_HOSTS_ARG]. Command aborted."
+      echo "----------------------------------------------------------------"
+      exit 1
+   fi
+else
+   # The -cluster option overrides VM_HOSTS
+   if [ "$CLUSTER_SPECIFIED" == "true" ]; then
+      if [ "`isClusterExist "$CLUSTER"`" == "false" ]; then 
+         echo "----------------------------------------------------------------"
+         echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+         echo >&2 "ERROR: Cluster does not exist [$CLUSTER]. Command aborted."
+         echo "----------------------------------------------------------------"
+         exit 1
+      fi
+      VM_ENABLED=`getClusterProperty "vm.enabled" "false"`
+      if [ "$VM_ENABLED" == "false" ]; then
+         echo "----------------------------------------------------------------"
+         echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+         echo >&2 "ERROR: Not a VM cluster [$CLUSTER]. To enable VMs, set the 'vm.enabled' property"
+         echo >&2 "       in the 'etc/cluster.properties' file."
+         echo "----------------------------------------------------------------"
+         exit 1
+      fi
+      VM_HOSTS=`getClusterProperty "vm.hosts"`
+      if [ "$VM_HOSTS" == "" ]; then
+         if [ "$VM_HOSTS" == "" ]; then
+            echo "----------------------------------------------------------------"
+            echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+            echo >&2 "    ERROR: The 'vm.hosts' property is not set in the 'etc/cluster.properties' file."
+            echo >&2 "           file. Command aborted."
+            echo "----------------------------------------------------------------"
+            exit 1
+         fi
+      fi
+   fi
+fi
+
+# Check file path
 FILE_PATH=${@: -1}
 ABS_PATH=$(getAbsPath "$FILE_PATH")
 if [ "$ABS_PATH" == "-1" ]; then
@@ -101,18 +158,22 @@ if [ "$ABS_PATH" == "-1" ]; then
    exit 1
 fi
 
+# Fail fast: Exit if any of the hosts is not reachable
+for VM_HOST in $__VM_HOSTS; do
+   REPLY=$(ssh -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o PasswordAuthentication=no "echo hello" 2>&1)
+   EXIT_CODE=$?
+   if [ "$EXIT_CODE" != "0" ]; then
+      echo -e "ERROR: $VM_HOST - ${CLightRed}Failed${CNone} ($REPLY)"
+      echo "       Command aborted."
+      exit 1
+   fi
+done
+
 # 
 # VM cluster
 #
-if [ "$VM_HOSTS" == "" ]; then
-   echo "----------------------------------------------------------------"
-   echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
-   if [ "$VM_HOSTS" == "" ]; then
-      echo >&2 "    ERROR: You must specify the '-vm' option or set VM_HOSTS in the workspace"
-      echo >&2 "           'setenv.sh' file. Command aborted."
-      exit 1
-   fi
-   echo "----------------------------------------------------------------"
+if [ "$VM_HOSTS_ARG" != "" ] && [[ "$VM_HOSTS_ARG" != *"-"* ]]; then
+   VM_HOSTS=$VM_HOSTS_ARG
 fi
 
 # Replace , with space
@@ -182,8 +243,19 @@ for VM_HOST in $__VM_HOSTS; do
    fi
 
    echo "   Copying to $VM_HOST..."
-   scp -q -r -o stricthostkeychecking=no $VM_KEY $ABS_PATH $VM_USER@$VM_HOST:$TO_PATH
+   if [ "$SIMULATE" == "true" ]; then
+      echo scp -q -r -o stricthostkeychecking=no $VM_KEY $ABS_PATH $VM_USER@$VM_HOST:$TO_PATH
+   else
+      scp -q -r -o stricthostkeychecking=no $VM_KEY $ABS_PATH $VM_USER@$VM_HOST:$TO_PATH
+   fi
 done
 
-echo "Copy complete."
-echo ""
+if [ "$SIMULATE" == "true" ]; then
+   echo "Simulation copy complete."
+elif [ "$VM_SPECIFIED" == "true" ]; then
+   echo "VM copy complete."
+elif [ "$CLUSTER_SPECIFIED" == "true" ]; then
+   echo "Cluster copy complete."
+else
+   echo "Workspace copy complete."
+fi
diff --git a/geode-addon-deployment/src/main/resources/bin_sh/vm_deploy_addon b/geode-addon-deployment/src/main/resources/bin_sh/vm_deploy_addon
--- a/geode-addon-deployment/src/main/resources/bin_sh/vm_deploy_addon
+++ b/geode-addon-deployment/src/main/resources/bin_sh/vm_deploy_addon
@@ -7,7 +7,7 @@ EXECUTABLE="`basename $0`"
 
 __options()
 {
-   echo "-vm -quiet -?"
+   echo "-cluster -vm -simulate -quiet -?"
 }
 
 if [ "$OPTIONS" == "true" ]; then
@@ -33,23 +33,36 @@ NAME
    $EXECUTABLE - Deploy the geode-addon distribution to VMs
 
 SYNOPSIS
-   $EXECUTABLE [-vm comma_separated_hosts] [-quiet] [-?]
+   $EXECUTABLE [-cluster cluster_name] [-vm comma_separated_hosts] [-simulate] [-quiet] [-?]
 
 DESCRIPTION
-   Deploys the geode-addon distribution to the specified VMs. It first scans
-   the VMs and displays the VMs that already have geode-addon installed. It
-   then prompt you to optionally overwrite the existing installations. The VMs'
+   Deploys the geode-addon distribution to all the VMs defined by the VM_HOSTS
+   environment variable in the workspace 'setenv.sh' file. To deploy to only the
+   cluster VMs, specify the cluster with the '-cluster' option. To deploy to a select
+   list of VMs, specify the VM list with the '-vm' option.
+
+   It first scans the VMs and displays the VMs that already have geode-addon installed.
+   It then prompts for optionally overwriting the existing installations. The VMs'
    geode-addon installation directory path is defined by VM_GEODE_ADDON_HOME
    set in the workspace 'setenv.sh' file.
 
-   If the '-vm' option is not specified, then it deploys to the hosts defined
-   by the VM_HOSTS environment variable set in the workspace 'setenv.sh' file.
-   
    $GEODE_ADDON_WORKSPACE/setenv.sh
 
+   Note that this command and all other commands that begin with the "vm_" preprefix are
+   available only on VM workspaces.
+
+   The '-vm' option overrides both the '-cluster' option and VM_HOSTS. The '-cluster' option
+   overrides VM_HOSTS. 
+   
 OPTIONS
+   -cluster cluster_name
+             Cluster name.
+
    -vm comma_separated_hosts
-             A list of VM hosts or addresses separated by comma. Spaces NOT allowed.
+             A comma separated list of VM hosts or addresses. Spaces NOT allowed.
+
+   -simulate
+             Print the remote commands but do not execute.
 
    -quiet
              Quiet mode. Supresses all interactive prompts.
@@ -72,6 +85,7 @@ EOF
    exit
 fi
 
+# Available only on VM workspaces
 if [ "$VM_ENABLED" != "true" ]; then
    echo "----------------------------------------------------------------"
    echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
@@ -80,15 +94,54 @@ if [ "$VM_ENABLED" != "true" ]; then
    exit 1 
 fi
 
+# If the -vm option is specified then it overrides all other options
+if [ "$VM_SPECIFIED" == "true" ]; then
+   if [ "$VM_HOSTS_ARG" != "" ] && [[ "$VM_HOSTS_ARG" != *"-"* ]]; then
+      VM_HOSTS=$VM_HOSTS_ARG
+   else
+      echo "----------------------------------------------------------------"
+      echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+      echo >&2 "ERROR: Invalid value for -vm [$VM_HOSTS_ARG]. Command aborted."
+      echo "----------------------------------------------------------------"
+      exit 1
+   fi
+else
+   # The -cluster option overrides VM_HOSTS
+   if [ "$CLUSTER_SPECIFIED" == "true" ]; then
+      if [ "`isClusterExist "$CLUSTER"`" == "false" ]; then 
+         echo "----------------------------------------------------------------"
+         echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+         echo >&2 "ERROR: Cluster does not exist [$CLUSTER]. Command aborted."
+         echo "----------------------------------------------------------------"
+         exit 1
+      fi
+      VM_ENABLED=`getClusterProperty "vm.enabled" "false"`
+      if [ "$VM_ENABLED" == "false" ]; then
+         echo "----------------------------------------------------------------"
+         echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+         echo >&2 "ERROR: Not a VM cluster [$CLUSTER]. To enable VMs, set the 'vm.enabled' property"
+         echo >&2 "       in the 'etc/cluster.properties' file."
+         echo "----------------------------------------------------------------"
+         exit 1
+      fi
+      VM_HOSTS=`getClusterProperty "vm.hosts"`
+      if [ "$VM_HOSTS" == "" ]; then
+         if [ "$VM_HOSTS" == "" ]; then
+            echo "----------------------------------------------------------------"
+            echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+            echo >&2 "    ERROR: The 'vm.hosts' property is not set in the 'etc/cluster.properties' file."
+            echo >&2 "           file. Command aborted."
+            echo "----------------------------------------------------------------"
+            exit 1
+         fi
+      fi
+   fi
+fi
+
 echo "----------------------------------------------------------------"
 echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
-if [ "$VM_HOSTS" == "" ]; then
-   echo "    ERROR: Neither '-vm' nor 'VM_HOSTS' defined. Command aborted."
-   exit 1
-fi
 echo "Deploying geode-addon to the following VM hosts:"
-echo "    $VM_HOSTS
-echo "   
+echo "    $VM_HOSTS"
 echo "----------------------------------------------------------------"
 
 # Replace , with space
@@ -100,11 +153,26 @@ if [ "$VM_KEY" != "" ]; then
    VM_KEY="-i $VM_KEY"
 fi
 
+# Fail fast: Exit if any of the hosts is not reachable
+for VM_HOST in $__VM_HOSTS; do
+   REPLY=$(ssh -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o PasswordAuthentication=no "echo hello" 2>&1)
+   EXIT_CODE=$?
+   if [ "$EXIT_CODE" != "0" ]; then
+      echo -e "ERROR: $VM_HOST - ${CLightRed}Failed${CNone} ($REPLY)"
+      echo "       Command aborted."
+      exit 1
+   fi
+done
+
+# Simulation runs in the quite mode
+if [ "$SIMULATE" == "true" ]; then
+   QUIET=$SIMULATE
+fi
+
 # Find all existing and new hosts
 EXISTING_HOSTS=
 NEW_HOSTS=
 THIS_VM_HOSTNAME=`hostname`
-echo "VM_GEODE_ADDON_HOME=$VM_GEODE_ADDON_HOME"
 COMMAND="if [ -d "$VM_GEODE_ADDON_HOME" ]; then echo true; else echo false; fi"
 EXISTING_HOST_COUNT=0
 NEW_HOST_COUNT=0
@@ -160,9 +228,8 @@ if [ "$QUIET" == "false" ]; then
    fi
 fi
 
-
 if [ $DEPLOYMENT_HOST_COUNT -eq 0 ]; then
-   echo "No qualified hosts. Command aborted." 
+   echo "No qualified hosts found. Command aborted." 
    echo ""
    exit
 fi
@@ -174,17 +241,25 @@ TAR_BALL_NAME=$ROOT_DIR_NAME.tar
 TAR_BALL_PATH=$GEODE_ADDON_WORKSPACE/bundles/$TAR_BALL_NAME
 VM_GEODE_ADDON_HOME_PARENT_DIR="$(dirname "$VM_GEODE_ADDON_HOME")"
 
-pushd $GEODE_ADDON_HOME/.. 
-tar czf $TAR_BALL_GZ_PATH $ROOT_DIR_NAME
-popd
+if [ "$SIMULATE" != "true" ]; then
+   pushd $GEODE_ADDON_HOME/.. 
+   tar czf $TAR_BALL_GZ_PATH $ROOT_DIR_NAME
+   popd
+fi
 
 if [ "$NEW_HOSTS" != "" ]; then
    echo "New Hosts:"
    for VM_HOST in $NEW_HOSTS; do
       echo "   Deploying to $VM_HOST..."
-      ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "mkdir -p $VM_GEODE_ADDON_HOME_PARENT_DIR"
-      scp -q -o stricthostkeychecking=no $VM_KEY $TAR_BALL_GZ_PATH $VM_USER@$VM_HOST:/tmp
-      ssh -q -n $VM_USER@$VM_HOST -o stricthostkeychecking=no "tar -C $VM_GEODE_ADDON_HOME_PARENT_DIR -xzf /tmp/$TAR_BALL_GZ_NAME; rm /tmp/$TAR_BALL_GZ_NAME"
+      if [ "$SIMULATE" == "true" ]; then
+         echo ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "mkdir -p $VM_GEODE_ADDON_HOME_PARENT_DIR"
+         echo scp -q -o stricthostkeychecking=no $VM_KEY $TAR_BALL_GZ_PATH $VM_USER@$VM_HOST:/tmp
+         echo ssh -q -n $VM_USER@$VM_HOST -o stricthostkeychecking=no "tar -C $VM_GEODE_ADDON_HOME_PARENT_DIR -xzf /tmp/$TAR_BALL_GZ_NAME; rm /tmp/$TAR_BALL_GZ_NAME"
+      else
+         ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "mkdir -p $VM_GEODE_ADDON_HOME_PARENT_DIR"
+         scp -q -o stricthostkeychecking=no $VM_KEY $TAR_BALL_GZ_PATH $VM_USER@$VM_HOST:/tmp
+         ssh -q -n $VM_USER@$VM_HOST -o stricthostkeychecking=no "tar -C $VM_GEODE_ADDON_HOME_PARENT_DIR -xzf /tmp/$TAR_BALL_GZ_NAME; rm /tmp/$TAR_BALL_GZ_NAME"
+      fi
    done
 fi
 
@@ -192,9 +267,18 @@ if [ "$EXISTING_HOSTS" != "" ]; then
    echo "Existing Hosts:"
    for VM_HOST in $EXISTING_HOSTS; do
       echo "   Deploying to $VM_HOST..."
-      scp -q -o stricthostkeychecking=no $VM_KEY $TAR_BALL_GZ_PATH $VM_USER@$VM_HOST:/tmp
-      ssh -q -n $VM_USER@$VM_HOST -o stricthostkeychecking=no "tar -C $VM_GEODE_ADDON_HOME_PARENT_DIR -xzf /tmp/$TAR_BALL_GZ_NAME; rm /tmp/$TAR_BALL_GZ_NAME"
+      if [ "$SIMULATE" == "true" ]; then
+         scp -q -o stricthostkeychecking=no $VM_KEY $TAR_BALL_GZ_PATH $VM_USER@$VM_HOST:/tmp
+         ssh -q -n $VM_USER@$VM_HOST -o stricthostkeychecking=no "tar -C $VM_GEODE_ADDON_HOME_PARENT_DIR -xzf /tmp/$TAR_BALL_GZ_NAME; rm /tmp/$TAR_BALL_GZ_NAME"
+      else
+         scp -q -o stricthostkeychecking=no $VM_KEY $TAR_BALL_GZ_PATH $VM_USER@$VM_HOST:/tmp
+         ssh -q -n $VM_USER@$VM_HOST -o stricthostkeychecking=no "tar -C $VM_GEODE_ADDON_HOME_PARENT_DIR -xzf /tmp/$TAR_BALL_GZ_NAME; rm /tmp/$TAR_BALL_GZ_NAME"
+      fi
    done
 fi
-echo "Deployment complete."
 echo ""
+if [ "$SIMULATE" == "true" ]; then
+   echo "Simulation deployment complete."
+else
+   echo "Deployment complete."
+fi
diff --git a/geode-addon-deployment/src/main/resources/bin_sh/vm_deploy_bundle b/geode-addon-deployment/src/main/resources/bin_sh/vm_deploy_bundle
--- a/geode-addon-deployment/src/main/resources/bin_sh/vm_deploy_bundle
+++ b/geode-addon-deployment/src/main/resources/bin_sh/vm_deploy_bundle
@@ -7,7 +7,7 @@ EXECUTABLE="`basename $0`"
 
 __options()
 {
-   echo "-cluster -vm -quiet -?"
+   echo "-cluster -vm -simulate -quiet -?"
 }
 
 if [ "$OPTIONS" == "true" ]; then
@@ -34,22 +34,31 @@ NAME
                  geode-addon environment
 
 SYNOPSIS
-   $EXECUTABLE [-cluster cluster_name] [-vm comma_separated_hosts] [-quiet] [-?] bundle_file
+   $EXECUTABLE [-cluster cluster_name] [-vm comma_separated_hosts] [-simulate] [-quiet] bundle_file [-?]
 
 DESCRIPTION
-   Deploys the specified bundle file to the specified VMs. The VMs must have
-   this version of geode-addon already installed in the same path. (To install
-   geode-addon on other VMs, use 'vm_copy' and 'vm_exec'.)
- 
-   If the '-vm' option is not specified, then it deploys to the hosts defined
-   by the 'vm.locator.hosts' and 'vm.hosts' properties in the etc/cluster.properties file.
+   Deploys the specified bundle file to all the VMs defined by the VM_HOSTS
+   environment variable in the workspace 'setenv.sh' file. To deploy to only the
+   cluster VMs, specify the cluster with the '-cluster' option. To deploy to a select
+   list of VMs, specify the VM list with the '-vm' option.
+
+   $GEODE_ADDON_WORKSPACE/setenv.sh
+
+   It prompts for confimration if the '-quiet' is not specified.
+
+   Note that this command and all other commands that begin with the "vm_" preprefix are
+   available only on VM workspaces.
+
+   The '-vm' option overrides both the '-cluster' option and VM_HOSTS. The '-cluster' option
+   overrides VM_HOSTS. 
 
 OPTIONS
-   -cluster cluster_name
-             Unique cluster name. The cluster name is prepended to all member names.
 
    -vm comma_separated_hosts
-             A list of VM hosts or addresses separated by comma. Spaces NOT allowed.
+             A comma separated list of VM hosts or addresses. Spaces NOT allowed.
+
+   -simulate
+             Print the remote commands but do not execute.
 
    -quiet
              Quiet mode. Supresses all interactive prompts.
@@ -75,6 +84,58 @@ EOF
    exit
 fi
 
+# Available only on VM workspaces
+if [ "$VM_ENABLED" != "true" ]; then
+   echo "----------------------------------------------------------------"
+   echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+   echo "    ERROR: The workspace is not a VM workspace. Command aborted."
+   echo "----------------------------------------------------------------"
+   exit 1 
+fi
+
+# If the -vm option is specified then it overrides all other options
+if [ "$VM_SPECIFIED" == "true" ]; then
+   if [ "$VM_HOSTS_ARG" != "" ] && [[ "$VM_HOSTS_ARG" != *"-"* ]]; then
+      VM_HOSTS=$VM_HOSTS_ARG
+   else
+      echo "----------------------------------------------------------------"
+      echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+      echo >&2 "ERROR: Invalid value for -vm [$VM_HOSTS_ARG]. Command aborted."
+      echo "----------------------------------------------------------------"
+      exit 1
+   fi
+else
+   # The -cluster option overrides VM_HOSTS
+   if [ "$CLUSTER_SPECIFIED" == "true" ]; then
+      if [ "`isClusterExist "$CLUSTER"`" == "false" ]; then 
+         echo "----------------------------------------------------------------"
+         echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+         echo >&2 "ERROR: Cluster does not exist [$CLUSTER]. Command aborted."
+         echo "----------------------------------------------------------------"
+         exit 1
+      fi
+      VM_ENABLED=`getClusterProperty "vm.enabled" "false"`
+      if [ "$VM_ENABLED" == "false" ]; then
+         echo "----------------------------------------------------------------"
+         echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+         echo >&2 "ERROR: Not a VM cluster [$CLUSTER]. To enable VMs, set the 'vm.enabled' property"
+         echo >&2 "       in the 'etc/cluster.properties' file."
+         echo "----------------------------------------------------------------"
+         exit 1
+      fi
+      VM_HOSTS=`getClusterProperty "vm.hosts"`
+      if [ "$VM_HOSTS" == "" ]; then
+         if [ "$VM_HOSTS" == "" ]; then
+            echo "----------------------------------------------------------------"
+            echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+            echo >&2 "    ERROR: The 'vm.hosts' property is not set in the 'etc/cluster.properties' file."
+            echo >&2 "           file. Command aborted."
+            echo "----------------------------------------------------------------"
+            exit 1
+         fi
+      fi
+   fi
+fi
 
 BUNDLE_FILE_PATH=${@: -1}
 if [ ! -f "$BUNDLE_FILE_PATH" ]; then
@@ -91,12 +152,16 @@ if [ "$VM_ENABLED" != "true" ]; then
    exit 1 
 fi
 
+if [ "$VM_HOSTS_ARG" != "" ] && [[ "$VM_HOSTS_ARG" != *"-"* ]]; then
+   VM_HOSTS=$VM_HOSTS_ARG
+fi
 if [ "$VM_HOSTS" == "" ]; then
    echo "----------------------------------------------------------------"
-   echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+   echo "WORKSPACE $GEODE_ADDON_WORKSPACE"
    if [ "$VM_HOSTS" == "" ]; then
       echo >&2 "    ERROR: You must specify the '-vm' option or set VM_HOSTS in the workspace"
       echo >&2 "           'setenv.sh' file. Command aborted."
+      echo "----------------------------------------------------------------"
       exit 1
    fi
    echo "----------------------------------------------------------------"
@@ -111,11 +176,27 @@ if [ "$VM_KEY" != "" ]; then
    VM_KEY="-i $VM_KEY"
 fi
 
+# Fail fast: Exit if any of the hosts is not reachable
+for VM_HOST in $__VM_HOSTS; do
+   REPLY=$(ssh -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o PasswordAuthentication=no "echo hello" 2>&1)
+   EXIT_CODE=$?
+   if [ "$EXIT_CODE" != "0" ]; then
+      echo -e "ERROR: $VM_HOST - ${CLightRed}Failed${CNone} ($REPLY)"
+      echo "       Command aborted."
+      exit 1
+   fi
+done
+
+# Simulation runs in the quite mode
+if [ "$SIMULATE" == "true" ]; then
+   QUIET=$SIMULATE
+fi
+
 # Find all existing and new hosts
 EXISTING_HOSTS=
 NEW_HOSTS=
 THIS_VM_HOSTNAME=`hostname`
-COMMAND="if [ -d "$BASE_DIR" ]; then echo true; else echo false; fi"
+COMMAND="if [ -d "$VM_GEODE_ADDON_HOME" ]; then echo true; else echo false; fi"
 EXISTING_HOST_COUNT=0
 NEW_HOST_COUNT=0
 for VM_HOST in $__VM_HOSTS; do
@@ -156,7 +237,7 @@ if [ "$QUIET" == "false" ]; then
 fi
 
 if [ $DEPLOYMENT_HOST_COUNT -eq 0 ]; then
-   echo "No qualified hosts. Command aborted." 
+   echo "No qualified hosts found. Command aborted." 
    echo ""
    exit
 fi
@@ -171,11 +252,21 @@ if [ "$EXISTING_HOSTS" != "" ]; then
    echo "Existing Hosts:"
    for VM_HOST in $EXISTING_HOSTS; do
       echo "   Deploying to $VM_HOST..."
-      ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "mkdir -p $BASE_DIR/bundle"
-      scp -q -o stricthostkeychecking=no $VM_KEY $BUNDLE_FILE_PATH $VM_USER@$VM_HOST:$BASE_DIR/bundle
-      ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "tar -C $BASE_DIR -xzf $BASE_DIR/bundle/$BUNDLE_FILE"
+      if [ "$SIMULATE" == "true" ]; then
+         echo ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "mkdir -p $VM_GEODE_ADDON_WORKSPACE/bundle"
+         echo scp -q -o stricthostkeychecking=no $VM_KEY $BUNDLE_FILE_PATH $VM_USER@$VM_HOST:$VM_GEODE_ADDON_WORKSPACE/bundle
+         echo ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "tar -C $VM_GEODE_ADDON_WORKSPACE -xzf $VM_GEODE_ADDON_WORKSPACE/bundle/$BUNDLE_FILE"
+      else
+         ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "mkdir -p $VM_GEODE_ADDON_WORKSPACE/bundle"
+         scp -q -o stricthostkeychecking=no $VM_KEY $BUNDLE_FILE_PATH $VM_USER@$VM_HOST:$VM_GEODE_ADDON_WORKSPACE/bundle
+         ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "tar -C $VM_GEODE_ADDON_WORKSPACE -xzf $VM_GEODE_ADDON_WORKSPACE/bundle/$BUNDLE_FILE"
+      fi
    done
 fi
 
-echo "Deployment complete."
 echo ""
+if [ "$SIMULATE" == "true" ]; then
+   echo "Simulation deployment complete."
+else
+   echo "Deployment complete."
+fi
diff --git a/geode-addon-deployment/src/main/resources/bin_sh/vm_download b/geode-addon-deployment/src/main/resources/bin_sh/vm_download
--- a/geode-addon-deployment/src/main/resources/bin_sh/vm_download
+++ b/geode-addon-deployment/src/main/resources/bin_sh/vm_download
@@ -7,7 +7,7 @@ EXECUTABLE="`basename $0`"
 
 __options()
 {
-   echo "-cluster -vm -key -?"
+   echo "-cluster -vm -?"
 }
 
 if [ "$OPTIONS" == "true" ]; then
@@ -33,34 +33,28 @@ NAME
    $EXECUTABLE - Download all the log and statistics files from the VMs to the local file system
 
 SYNOPSIS
-   $EXECUTABLE [-cluster cluster_name] [-key private_key_file] [-vm comma_separated_hosts] [-mirror] [-?] file_path
+   $EXECUTABLE [-cluster cluster_name] [-vm comma_separated_hosts] [-?]
 
 DESCRIPTION
    Downloads the log and statistics files from the VMs to the local cluster's
    'log' and 'stats' directories.
 
    If the '-vm' option is not specified, then it downloads the log and statistics files
-   from the hosts defined by the 'vm.locator.hosts' and 'vm.hosts' in the 'etc/cluster.properties'
-   file.
+   from the hosts defined by the 'vm.locator.hosts' and 'vm.hosts' properties in the
+   'etc/cluster.properties' file.
 
 OPTIONS
+   -cluster cluster_name
+             Cluster name.
 
-    -cluster cluster_name
-              Cluster name.
-
-    -vm comma_separated_hosts
-              A list of VM hosts or addresses separated by comma. Spaces NOT allowed.
-
-    -key private_key_file
-              Private key file path. To ssh into your VM such as the ones on AWS, you may
-              supply your private key file. Normally, the private key file is not
-              required if you have set public-key authentication.
+   -vm comma_separated_hosts
+             A comma separated list of VM hosts or addresses. Spaces NOT allowed.
 
 EOF
 if [ "$MAN_SPECIFIED" == "false" ]; then
 cat <<EOF
 DEFAULT
-   $EXECUTABLE -cluster $CLUSTER file_path
+   $EXECUTABLE -cluster $CLUSTER
 EOF
 fi
 cat <<EOF
@@ -71,6 +65,15 @@ EOF
    exit
 fi
 
+if [ "$VM_ENABLED" != "true" ]; then
+   echo "----------------------------------------------------------------"
+   echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+   echo "    ERROR: The workspace is not a VM workspace. Command aborted."
+   echo "----------------------------------------------------------------"
+   exit 1 
+fi
+
+# Make sure the cluster is VM enabled
 VM_ENABLED=`getClusterProperty "vm.enabled" "false"`
 if [ "$VM_ENABLED" == "false" ]; then
    echo >&2 "ERROR: Not a VM cluster [$CLUSTER]. To enable VMs, set the 'vm.enabled' property"
@@ -81,7 +84,7 @@ fi
 # 
 # VM cluster
 #
-if [ "$VM_SPECIFIED" == "true" ]; then
+if [ "$VM_HOSTS_ARG" != "" ] && [[ "$VM_HOSTS_ARG" != *"-"* ]]; then
    VM_HOSTS=$VM_HOSTS_ARG
 else
    VM_HOSTS=$(getAllMergedVmHosts)
@@ -90,8 +93,8 @@ if [ "$VM_HOSTS" == "" ]; then
    echo "----------------------------------------------------------------"
    echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
    if [ "$VM_HOSTS" == "" ]; then
-      echo >&2 "    ERROR: You must specify the '-vm' option or set VM_HOSTS in the workspace"
-      echo >&2 "           'setenv.sh' file. Command aborted."
+      echo >&2 "    ERROR: You must specify the '-vm' option or set the 'vm.hosts' property"
+      echo >&2 "           in the 'etc/cluster.properties' file. Command aborted."
       exit 1
    fi
    echo "----------------------------------------------------------------"
@@ -136,7 +139,6 @@ if [ ! -d "$STATS_DIR" ]; then
    mkdir -p $STATS_DIR
 fi
 
-
 for VM_HOST in $__VM_HOSTS; do
    if [ "$VM_HOST" == "$THIS_VM_HOSTNAME" ]; then
       continue
@@ -161,4 +163,3 @@ echo "   $LOG_DIR"
 echo "   $STATS_DIR"
 echo ""
 echo "Download complete."
-echo ""
diff --git a/geode-addon-deployment/src/main/resources/bin_sh/vm_exec b/geode-addon-deployment/src/main/resources/bin_sh/vm_exec
--- a/geode-addon-deployment/src/main/resources/bin_sh/vm_exec
+++ b/geode-addon-deployment/src/main/resources/bin_sh/vm_exec
@@ -7,7 +7,7 @@ EXECUTABLE="`basename $0`"
 
 __options()
 {
-   echo "-cluster -vm -all -debug -?"
+   echo "-cluster -vm -all -simulate -?"
 }
 
 if [ "$OPTIONS" == "true" ]; then
@@ -26,31 +26,38 @@ NAME
                  by default in geode-addon environment
 
 SYNOPSIS
-   $EXECUTABLE [-cluster cluster_name] [-vm comma_separated_hosts] [-all] [-debug] "<commands>" [-?]
+   $EXECUTABLE [-cluster cluster_name] [-vm comma_separated_hosts] [-all] [-simulate] "commands" [-?]
 
-   Executes the specified command in the specified VMs. By default, the VM in 
-   which this command executes is not included. To include t, specify the '-all' option.
- 
-   If the '-vm' option is not specified, then it executes the command in the
-   hosts defined by the 'vm.locator.hosts' and 'vm.hosts' properties in the
-   etc/cluster.properties file.
+   Executes the specified commands in all the workspace VMs defined by the VM_HOSTS
+   environment variable in the workspace 'setenv.sh' file. To execute only in the
+   cluster VMs, specify the cluster with the '-cluster' option. To execute in a select
+   list of VMs, specify the VM list with the '-vm' option.
+
+   The specified commands will not be executed on this VM (the VM from which $EXECUTABLE
+   is executed). To include this VM, specify the '-all' option.
+
+   Note that this command and all other commands that begin with the "vm_" preprefix are
+   available only on VM workspaces.
+
+   The '-vm' option overrides both the '-cluster' option and VM_HOSTS. The '-cluster' option
+   overrides VM_HOSTS. 
 
 OPTIONS
    -cluster cluster_name
              Cluster name.
 
    -vm comma_separated_hosts
-             A list of VM hosts or addresses separated by comma. Spaces NOT allowed.
+             A comma separated list of VM hosts or addresses. Spaces NOT allowed.
 
    -all
              Execute the command on all VMs including this VM. If not specified
-             then the command will not executed on this VM.
+             then the command will not execute on this VM.
 
-   -debug
-             Print the remote command but do not execute.
+   -simulate
+             Print the remote commands but do not execute.
 
    "commands"
-             Remote commands separated by ';'. Commands should be in double quotes.
+             Remote commands separated by ';' or '&&'. Commands should be in double quotes.
 
 EOF
 if [ "$MAN_SPECIFIED" == "false" ]; then
@@ -67,18 +74,57 @@ EOF
    exit
 fi
 
-# 
-# VM cluster
-#
-if [ "$VM_HOSTS" == "" ]; then
+# Available only on VM workspaces
+if [ "$VM_ENABLED" != "true" ]; then
    echo "----------------------------------------------------------------"
    echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
-   if [ "$VM_HOSTS" == "" ]; then
-      echo >&2 "    ERROR: You must specify the '-vm' option or set VM_HOSTS in the workspace"
-      echo >&2 "           'setenv.sh' file. Command aborted."
+   echo "    ERROR: The workspace is not a VM workspace. Command aborted."
+   echo "----------------------------------------------------------------"
+   exit 1 
+fi
+
+# If the -vm option is specified then it overrides all other options
+if [ "$VM_SPECIFIED" == "true" ]; then
+   if [ "$VM_HOSTS_ARG" != "" ] && [[ "$VM_HOSTS_ARG" != *"-"* ]]; then
+      VM_HOSTS=$VM_HOSTS_ARG
+   else
+      echo "----------------------------------------------------------------"
+      echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+      echo >&2 "ERROR: Invalid value for -vm [$VM_HOSTS_ARG]. Command aborted."
+      echo "----------------------------------------------------------------"
       exit 1
    fi
-   echo "----------------------------------------------------------------"
+else
+   # The -cluster option overrides VM_HOSTS
+   if [ "$CLUSTER_SPECIFIED" == "true" ]; then
+      if [ "`isClusterExist "$CLUSTER"`" == "false" ]; then 
+         echo "----------------------------------------------------------------"
+         echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+         echo >&2 "ERROR: Cluster does not exist [$CLUSTER]. Command aborted."
+         echo "----------------------------------------------------------------"
+         exit 1
+      fi
+      VM_ENABLED=`getClusterProperty "vm.enabled" "false"`
+      if [ "$VM_ENABLED" == "false" ]; then
+         echo "----------------------------------------------------------------"
+         echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+         echo >&2 "ERROR: Not a VM cluster [$CLUSTER]. To enable VMs, set the 'vm.enabled' property"
+         echo >&2 "       in the 'etc/cluster.properties' file."
+         echo "----------------------------------------------------------------"
+         exit 1
+      fi
+      VM_HOSTS=`getClusterProperty "vm.hosts"`
+      if [ "$VM_HOSTS" == "" ]; then
+         if [ "$VM_HOSTS" == "" ]; then
+            echo "----------------------------------------------------------------"
+            echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+            echo >&2 "    ERROR: The 'vm.hosts' property is not set in the 'etc/cluster.properties' file."
+            echo >&2 "           file. Command aborted."
+            echo "----------------------------------------------------------------"
+            exit 1
+         fi
+      fi
+   fi
 fi
 
 #
@@ -86,13 +132,12 @@ fi
 #
 COMMAND=
 PREV_VAL=
-for i in $*
-do
+for i in $*; do
    if [[ "$i" == "${CLUSTER}" ]]; then
        if [ -z $CLUSTER_SPECIFIED ]; then
           COMMAND="$COMMAND $i"
        fi
-   elif [[ "$i" != "-cluster" ]]  && [[ "$i" != "-vm" ]]  && [[ "$i" != "-all" ]] && [[ "$i" != "-debug" ]]; then
+   elif [[ "$i" != "-cluster" ]]  && [[ "$i" != "-vm" ]]  && [[ "$i" != "-all" ]] && [[ "$i" != "-simulate" ]]; then
       if [ "$PREV_VAL" != "-vm" ]; then
          COMMAND="$COMMAND $i"
       fi
@@ -102,9 +147,13 @@ done
 
 # Replace , with space
 __VM_HOSTS=$(echo "$VM_HOSTS" | sed "s/,/ /g")
-DEFAULT_USER=$(whoami)
-VM_USER=`getClusterProperty "vm.user" "$DEFAULT_USER"`
-VM_KEY=`getClusterProperty "vm.privateKeyFile"`
+if [ "$CLUSTER_SPECIFIED" == "true" ]; then
+   VM_USER=`getClusterProperty "vm.user"`
+   VM_KEY=`getClusterProperty "vm.privateKeyFile"`
+fi
+if [ "$VM_USER" == "" ]; then
+   VM_USER=$(whoami)
+fi
 if [ "$VM_KEY" != "" ]; then 
    VM_KEY="-i $VM_KEY"
 fi
@@ -116,10 +165,13 @@ for VM_HOST in $__VM_HOSTS; do
      fi
 
      echo "---------- $VM_HOST ----------"
-     echo
-     if [ "$DEBUG" == "true" ]; then
+     if [ "$SIMULATE" == "true" ]; then
          echo "ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no $COMMAND"
+     else
+        ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no $COMMAND
      fi
-     ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no $COMMAND
      echo ""
 done
+if [ "$SIMULATE" == "true" ]; then
+   echo "Simulation complete."
+fi
diff --git a/geode-addon-deployment/src/main/resources/bin_sh/vm_install b/geode-addon-deployment/src/main/resources/bin_sh/vm_install
--- a/geode-addon-deployment/src/main/resources/bin_sh/vm_install
+++ b/geode-addon-deployment/src/main/resources/bin_sh/vm_install
@@ -7,7 +7,7 @@ EXECUTABLE="`basename $0`"
 
 __options()
 {
-   echo "-java -geode -vm -key -?"
+   echo "-java -geode -vm -simulate -?"
 }
 
 if [ "$OPTIONS" == "true" ]; then
@@ -30,36 +30,41 @@ WORKSPACE
    $GEODE_ADDON_WORKSPACE
 
 NAME
-   $EXECUTABLE - Install Geode/GemFire and Java remotely on the workspace VMs
+   $EXECUTABLE - Install Geode/GemFire and/or Java remotely on the workspace VMs
 
 SYNOPSIS
-   $EXECUTABLE [-vm comma_separated_hosts] [-key private_key_file] 
+   $EXECUTABLE [-vm comma_separated_hosts]
                [-java jdk_distribution_file]
-               [-geode imdg_or_jet_distribution_file]
-               [-?]
+               [-geode geode_or_gemfire_distribution_file]
+               [-simulate] [-?]
 
 DESCRIPTION
-  Installs the specified Geode and/or Java remotely on the workspace VMs.
+   Installs the specified Geode and/or Java remotely on all the VMs defined by
+   the VM_HOSTS environment variable in the workspace 'setenv.sh' file. To install 
+   only on the cluster VMs, specify the cluster with the '-cluster' option. To
+   install on a select list of VMs, specify the VM list with the '-vm' option.
 
-  If the '-vm' option is not specified, then it installs the specified file(s) to
-  the hosts defined by the VM_HOSTS environment variable in the workspace 'setenv.sh'
-  file.
+   Note that this command and all other commands that begin with the "vm_" preprefix are
+   available only on VM workspaces.
+
+   The '-vm' option overrides both the '-cluster' option and VM_HOSTS. The '-cluster' option
+   overrides VM_HOSTS. 
 
 OPTIONS
+   -cluster cluster_name
+             Cluster name.
 
-    -vm comma_separated_hosts
-              A list of VM hosts or addresses separated by comma. Spaces NOT allowed.
+   -vm comma_separated_hosts
+              A comma separated list of VM hosts or addresses. Spaces NOT allowed.
 
-    -key private_key_file
-              Private key file path. To ssh into your VM such as the ones on AWS, you may
-              supply your private key file. Normally, the private key file is not
-              required if you have set public-key authentication.
-
-    -java java_distribution_file
+   -java java_distribution_file
               JDK distribution file, e.g. jdk-8u212-linux-x64.tar.gz
 
-    -geode imdg_or_jet_distribution_file
-              Geode distribution file, e.g. geode-enterprise-3.12.5.tar.gz.
+   -geode geode_or_gemfire_distribution_file
+              Geode/GemFire distribution file, e.g., apache-geode-1.11.0.tgz or pivotal-gemfire-9.9.1.tgz
+
+   -simulate
+             Print the remote commands but do not execute.
 
 EOF
 if [ "$MAN_SPECIFIED" == "false" ]; then
@@ -74,6 +79,64 @@ SEE ALSO
 EOF
    printSeeAlsoList "vm_*" $EXECUTABLE
    exit
+fi
+
+if [ "$JAVA_HOME_ARG" == "" ] && [ "$GEODE_ARG" == "" ]; then
+   echo >&2 "ERROR: Must specify -java or -geode. Command aborted."
+   exit 1
+fi
+
+# Available only on VM workspaces
+if [ "$VM_ENABLED" != "true" ]; then
+   echo "----------------------------------------------------------------"
+   echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+   echo "    ERROR: The workspace is not a VM workspace. Command aborted."
+   echo "----------------------------------------------------------------"
+   exit 1 
+fi
+
+# If the -vm option is specified then it overrides all other options
+if [ "$VM_SPECIFIED" == "true" ]; then
+   if [ "$VM_HOSTS_ARG" != "" ] && [[ "$VM_HOSTS_ARG" != *"-"* ]]; then
+      VM_HOSTS=$VM_HOSTS_ARG
+   else
+      echo "----------------------------------------------------------------"
+      echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+      echo >&2 "ERROR: Invalid value for -vm [$VM_HOSTS_ARG]. Command aborted."
+      echo "----------------------------------------------------------------"
+      exit 1
+   fi
+else
+   # The -cluster option overrides VM_HOSTS
+   if [ "$CLUSTER_SPECIFIED" == "true" ]; then
+      if [ "`isClusterExist "$CLUSTER"`" == "false" ]; then 
+         echo "----------------------------------------------------------------"
+         echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+         echo >&2 "ERROR: Cluster does not exist [$CLUSTER]. Command aborted."
+         echo "----------------------------------------------------------------"
+         exit 1
+      fi
+      VM_ENABLED=`getClusterProperty "vm.enabled" "false"`
+      if [ "$VM_ENABLED" == "false" ]; then
+         echo "----------------------------------------------------------------"
+         echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+         echo >&2 "ERROR: Not a VM cluster [$CLUSTER]. To enable VMs, set the 'vm.enabled' property"
+         echo >&2 "       in the 'etc/cluster.properties' file."
+         echo "----------------------------------------------------------------"
+         exit 1
+      fi
+      VM_HOSTS=`getClusterProperty "vm.hosts"`
+      if [ "$VM_HOSTS" == "" ]; then
+         if [ "$VM_HOSTS" == "" ]; then
+            echo "----------------------------------------------------------------"
+            echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+            echo >&2 "    ERROR: The 'vm.hosts' property is not set in the 'etc/cluster.properties' file."
+            echo >&2 "           file. Command aborted."
+            echo "----------------------------------------------------------------"
+            exit 1
+         fi
+      fi
+   fi
 fi
 
 # Replace , with space
@@ -94,6 +157,17 @@ if [ "$KEY" != "" ]; then
    VM_KEY="-i $KEY"
 fi
 
+# Fail fast: Exit if any of the hosts is not reachable
+for VM_HOST in $__VM_HOSTS; do
+   REPLY=$(ssh -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o PasswordAuthentication=no "echo hello" 2>&1)
+   EXIT_CODE=$?
+   if [ "$EXIT_CODE" != "0" ]; then
+      echo -e "ERROR: $VM_HOST - ${CLightRed}Failed${CNone} ($REPLY)"
+      echo "       Command aborted."
+      exit 1
+   fi
+done
+
 # Determine all VMs that do not have Java and Geode installed.
 JAVA_HOME_COMMAND="if [ -d "$VM_JAVA_HOME" ]; then echo true; else echo false; fi"
 GEODE_HOME_COMMAND="if [ -d "$VM_GEODE_HOME" ]; then echo true; else echo false; fi"
@@ -102,17 +176,21 @@ GEODE_HOME_NOT_FOUND_LIST=""
 for VM_HOST in $__VM_HOSTS; do
    JAVA_HOME_EXISTS=$(ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "$JAVA_HOME_COMMAND")
    GEODE_HOME_EXISTS=$(ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "$GEODE_HOME_COMMAND")
-   if [ "$JAVA_HOME_EXISTS" == "false" ]; then
+   if [[ "$JAVA_HOME_EXISTS" == *"false" ]]; then
       JAVA_HOME_NOT_FOUND_LIST="$JAVA_HOME_NOT_FOUND_LIST $VM_HOST"
    fi
-   if [ "$GEODE_HOME_EXISTS" == "false" ]; then
+   if [[ "$GEODE_HOME_EXISTS" == *"false" ]]; then
       GEODE_HOME_NOT_FOUND_LIST="$GEODE_HOME_NOT_FOUND_LIST $VM_HOST"
    fi
 done
 
 echo ""
-PRIVATE_KEY_FILE_NAME=$(basename $VM_PRIVATE_KEY_FILE)
-REMOTE_VM_KEY=$VM_GEODE_ADDON_WORKSPACE/$PRIVATE_KEY_FILE_NAME
+
+REMOTE_VM_KEY=""
+if [ "$VM_PRIVATE_KEY_FILE" != "" ]; then
+   PRIVATE_KEY_FILE_NAME=$(basename $VM_PRIVATE_KEY_FILE)
+   REMOTE_VM_KEY=$VM_GEODE_ADDON_WORKSPACE/$PRIVATE_KEY_FILE_NAME
+fi
 
 #
 # Installs the product defined by the following variables
@@ -157,17 +235,29 @@ function installProduct
             break
          done
 	 # Upload to the base VM
-         scp -q -r -o stricthostkeychecking=no $VM_KEY $PRODUCT_PATH $VM_USER@$BASE_VM:/tmp/
+         if [ "$SIMULATE" == "true" ]; then
+            echo scp -q -r -o stricthostkeychecking=no $VM_KEY $PRODUCT_PATH $VM_USER@$BASE_VM:/tmp/
+         else
+            scp -q -r -o stricthostkeychecking=no $VM_KEY $PRODUCT_PATH $VM_USER@$BASE_VM:/tmp/
+	 fi
       fi
 
       for VM_HOST in $PRODUCT_HOME_NOT_FOUND_LIST; do
          if [ "$VM_HOST" != "$BASE_VM" ]; then
             echo "   Installing $VM_HOST..."
             # Copy from the base VM
-            ssh -q -n $VM_KEY $VM_USER@$BASE_VM -o stricthostkeychecking=no "scp -o stricthostkeychecking=no -i $REMOTE_VM_KEY /tmp/$__PRODUCT_DIST_FILE_NAME $VM_USER@$VM_HOST:/tmp/"
+            if [ "$SIMULATE" == "true" ]; then
+               echo ssh -q -n $VM_KEY $VM_USER@$BASE_VM -o stricthostkeychecking=no "scp -o stricthostkeychecking=no -i $REMOTE_VM_KEY /tmp/$__PRODUCT_DIST_FILE_NAME $VM_USER@$VM_HOST:/tmp/"
+            else
+               ssh -q -n $VM_KEY $VM_USER@$BASE_VM -o stricthostkeychecking=no "scp -o stricthostkeychecking=no -i $REMOTE_VM_KEY /tmp/$__PRODUCT_DIST_FILE_NAME $VM_USER@$VM_HOST:/tmp/"
+	    fi
          fi
 	 # Install
-         ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "tar -C $__PRODUCT_PARENT_PATH/ -xzf /tmp/$__PRODUCT_DIST_FILE_NAME"
+         if [ "$SIMULATE" == "true" ]; then
+            echo ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "tar -C $__PRODUCT_PARENT_PATH/ -xzf /tmp/$__PRODUCT_DIST_FILE_NAME"
+         else
+            ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "tar -C $__PRODUCT_PARENT_PATH/ -xzf /tmp/$__PRODUCT_DIST_FILE_NAME"
+	 fi
 
 	 # Remove
          #ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "rm /tmp/$__PRODUCT_DIST_FILE_NAME"
@@ -193,7 +283,7 @@ fi
 # Install Geode
 if [ "$GEODE_ARG" != "" ]; then
    # Arguments to installProduct function
-   PRODUCT="Goede"
+   PRODUCT="Geode"
    PRODUCT_HOME_NOT_FOUND_LIST=$GEODE_HOME_NOT_FOUND_LIST
    PRODUCT_PATH=$GEODE_ARG
    VM_PRODUCT_HOME=$VM_GEODE_HOME
@@ -203,3 +293,6 @@ fi
 
 echo "Run 'vm_test' to check installation and configuration status."
 echo ""
+if [ "$SIMULATE" == "true" ]; then
+   echo "Simulation complete."
+fi
diff --git a/geode-addon-deployment/src/main/resources/bin_sh/vm_sync b/geode-addon-deployment/src/main/resources/bin_sh/vm_sync
--- a/geode-addon-deployment/src/main/resources/bin_sh/vm_sync
+++ b/geode-addon-deployment/src/main/resources/bin_sh/vm_sync
@@ -30,25 +30,32 @@ WORKSPACE
    $GEODE_ADDON_WORKSPACE
 
 NAME
-   $EXECUTABLE - Synchronize the currrent workspace with the VM workspaces
+   $EXECUTABLE - Synchronize the rmote VMs with the local workspace
 
 SYNOPSIS
-   $EXECUTABLE [-vm comma_separated_hosts] [-?]
+   $EXECUTABLE [-cluster cluster_name] [-vm comma_separated_hosts] [-simulate] [-?]
 
 DESCRIPTION
-   Synchronizes the current workspace with VM workspaces. If the VM workspaces
-   do not exist then it remotely creates and synchronizes them. The VM workspace
-   path is defined by VM_GEODE_ADDON_WORKSPACE in the workspace 'setenv.sh' file.
+   Synchronizes all the VMs defined by VM_HOSTS environment variable in the workspace
+   'setenv.sh' file with the local workspace. To synchronize only the cluster VMs, specify
+   the cluster with the '-cluster' option. To synchronize a select list of VMs, specify
+   the VM list with the '-vm' option.
 
-   If the '-vm' option is not specified, then it deploys to the hosts defined
-   by the VM_HOSTS environment variable set in the workspace 'setenv.sh' file.
-   
-   $GEODE_ADDON_WORKSPACE/setenv.sh
+   Note that this command and all other commands that begin with the "vm_" preprefix are
+   available only on VM workspaces.
+
+   The '-vm' option overrides both the '-cluster' option and VM_HOSTS. The '-cluster' option
+   overrides VM_HOSTS. 
 
 OPTIONS
+   -cluster cluster_name
+             Cluster name.
 
-    -vm comma_separated_hosts
-              A list of VM hosts or addresses separated by comma. Spaces NOT allowed.
+   -vm comma_separated_hosts
+             A comma separated list of VM hosts or addresses. Spaces NOT allowed.
+
+   -simulate
+             Print the remote commands but do not execute.
 
 EOF
 if [ "$MAN_SPECIFIED" == "false" ]; then
@@ -65,12 +72,60 @@ EOF
    exit
 fi
 
-WORKSPACE_NAME=$(basename "$GEODE_ADDON_WORKSPACE")
-
+# Available only on VM workspaces
 if [ "$VM_ENABLED" != "true" ]; then
-   echo >&2 "ERROR: The cuurent workspace is not VM enabled [$WORKSPACE_NAME]. Command aborted."
-   exit 1
+   echo "----------------------------------------------------------------"
+   echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+   echo "    ERROR: The workspace is not a VM workspace. Command aborted."
+   echo "----------------------------------------------------------------"
+   exit 1 
 fi
+
+# If the -vm option is specified then it overrides all other options
+if [ "$VM_SPECIFIED" == "true" ]; then
+   if [ "$VM_HOSTS_ARG" != "" ] && [[ "$VM_HOSTS_ARG" != *"-"* ]]; then
+      VM_HOSTS=$VM_HOSTS_ARG
+   else
+      echo "----------------------------------------------------------------"
+      echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+      echo >&2 "ERROR: Invalid value for -vm [$VM_HOSTS_ARG]. Command aborted."
+      echo "----------------------------------------------------------------"
+      exit 1
+   fi
+else
+   # The -cluster option overrides VM_HOSTS
+   if [ "$CLUSTER_SPECIFIED" == "true" ]; then
+      if [ "`isClusterExist "$CLUSTER"`" == "false" ]; then 
+         echo "----------------------------------------------------------------"
+         echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+         echo >&2 "ERROR: Cluster does not exist [$CLUSTER]. Command aborted."
+         echo "----------------------------------------------------------------"
+         exit 1
+      fi
+      VM_ENABLED=`getClusterProperty "vm.enabled" "false"`
+      if [ "$VM_ENABLED" == "false" ]; then
+         echo "----------------------------------------------------------------"
+         echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+         echo >&2 "ERROR: Not a VM cluster [$CLUSTER]. To enable VMs, set the 'vm.enabled' property"
+         echo >&2 "       in the 'etc/cluster.properties' file."
+         echo "----------------------------------------------------------------"
+         exit 1
+      fi
+      VM_HOSTS=`getClusterProperty "vm.hosts"`
+      if [ "$VM_HOSTS" == "" ]; then
+         if [ "$VM_HOSTS" == "" ]; then
+            echo "----------------------------------------------------------------"
+            echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+            echo >&2 "    ERROR: The 'vm.hosts' property is not set in the 'etc/cluster.properties' file."
+            echo >&2 "           file. Command aborted."
+            echo "----------------------------------------------------------------"
+            exit 1
+         fi
+      fi
+   fi
+fi
+
+WORKSPACE_NAME=$(basename "$GEODE_ADDON_WORKSPACE")
 
 # Replace , with space
 __VM_HOSTS=$(echo "$VM_HOSTS" | sed "s/,/ /g")
@@ -90,6 +145,17 @@ if [ "$KEY" != "" ]; then
    VM_KEY="-i $KEY"
 fi
 
+# Fail fast: Exit if any of the hosts is not reachable
+for VM_HOST in $__VM_HOSTS; do
+   REPLY=$(ssh -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o PasswordAuthentication=no "echo hello" 2>&1)
+   EXIT_CODE=$?
+   if [ "$EXIT_CODE" != "0" ]; then
+      echo -e "ERROR: $VM_HOST - ${CLightRed}Failed${CNone} ($REPLY)"
+      echo "       Command aborted."
+      exit 1
+   fi
+done
+
 # Check if we need to deploy geode-addon to any of the VMs
 ADDON_COMMAND="if [ -d "$VM_GEODE_ADDON_HOME" ]; then echo true; else echo false; fi"
 JAVA_COMMAND="if [ -d "$VM_JAVA_HOME" ]; then echo true; else echo false; fi"
@@ -98,7 +164,7 @@ INSTALL_ADDON_HOST_LIST=""
 for VM_HOST in $__VM_HOSTS; do
    # geode-addon
    ADDON_EXISTS=$(ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "$ADDON_COMMAND")
-   if [ "$ADDON_EXISTS" == "false" ]; then
+   if [[ "$ADDON_EXISTS" == *"false" ]]; then
       INSTALL_ADDON_HOST_LIST="$INSTALL_ADDON_HOST_LIST $VM_HOST"
    fi
 done
@@ -113,9 +179,15 @@ if [ "$INSTALL_ADDON_HOST_LIST" != "" ]; then
 
    for VM_HOST in $INSTALL_ADDON_HOST_LIST; do
       echo "Deploying $ROOT_DIR_NAME to $VM_HOST..."
-      ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "mkdir -p $VM_GEODE_ADDON_HOME_PARENT_DIR"
-      scp -q -o stricthostkeychecking=no $VM_KEY $TAR_BALL_GZ_PATH $VM_USER@$VM_HOST:/tmp
-      ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "tar -C $VM_GEODE_ADDON_HOME_PARENT_DIR -xzf /tmp/$TAR_BALL_GZ_NAME; rm /tmp/$TAR_BALL_GZ_NAME"
+      if [ "$SIMULATE" == "true" ]; then
+         echo ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "mkdir -p $VM_GEODE_ADDON_HOME_PARENT_DIR"
+         echo scp -q -o stricthostkeychecking=no $VM_KEY $TAR_BALL_GZ_PATH $VM_USER@$VM_HOST:/tmp
+         echo ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "tar -C $VM_GEODE_ADDON_HOME_PARENT_DIR -xzf /tmp/$TAR_BALL_GZ_NAME; rm /tmp/$TAR_BALL_GZ_NAME"
+      else
+         ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "mkdir -p $VM_GEODE_ADDON_HOME_PARENT_DIR"
+         scp -q -o stricthostkeychecking=no $VM_KEY $TAR_BALL_GZ_PATH $VM_USER@$VM_HOST:/tmp
+         ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "tar -C $VM_GEODE_ADDON_HOME_PARENT_DIR -xzf /tmp/$TAR_BALL_GZ_NAME; rm /tmp/$TAR_BALL_GZ_NAME"
+      fi
    done
 fi
 
@@ -167,26 +239,41 @@ for VM_HOST in $__VM_HOSTS; do
    fi
 
    echo "   Synchronizing $VM_HOST..."
-   ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "mkdir -p $VM_GEODE_ADDON_WORKSPACE"
-   scp -q -r -o stricthostkeychecking=no $VM_KEY /tmp/vm_sync.tar.gz $VM_USER@$VM_HOST:/tmp/
-   ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "tar -C $VM_GEODE_ADDON_WORKSPACE -xzf /tmp/vm_sync.tar.gz; rm /tmp/vm_sync.tar.gz"
-   scp -q -o stricthostkeychecking=no $VM_KEY /tmp/setenv.sh $VM_USER@$VM_HOST:$VM_GEODE_ADDON_WORKSPACE/
+   if [ "$SIMULATE" == "true" ]; then
+      echo ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "mkdir -p $VM_GEODE_ADDON_WORKSPACE"
+      echo scp -q -r -o stricthostkeychecking=no $VM_KEY /tmp/vm_sync.tar.gz $VM_USER@$VM_HOST:/tmp/
+      echo ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "tar -C $VM_GEODE_ADDON_WORKSPACE -xzf /tmp/vm_sync.tar.gz; rm /tmp/vm_sync.tar.gz"
+      echo scp -q -o stricthostkeychecking=no $VM_KEY /tmp/setenv.sh $VM_USER@$VM_HOST:$VM_GEODE_ADDON_WORKSPACE/
+   else
+      ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "mkdir -p $VM_GEODE_ADDON_WORKSPACE"
+      scp -q -r -o stricthostkeychecking=no $VM_KEY /tmp/vm_sync.tar.gz $VM_USER@$VM_HOST:/tmp/
+      ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "tar -C $VM_GEODE_ADDON_WORKSPACE -xzf /tmp/vm_sync.tar.gz && rm /tmp/vm_sync.tar.gz"
+      scp -q -o stricthostkeychecking=no $VM_KEY /tmp/setenv.sh $VM_USER@$VM_HOST:$VM_GEODE_ADDON_WORKSPACE/
+   fi
 
    # Configure the workspaces directory if not configured already
    INITENV_EXISTS=$(ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "$INITENV_COMMAND")
    ADDONENV_EXISTS=$(ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "$ADDONENV_COMMAND")
    SETENV_EXISTS=$(ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "$SETENV_COMMAND")
 
-   if [ "$INITENV_EXISTS" != "true" ]; then
+   if [[ "$INITENV_EXISTS" == *"false" ]]; then
       scp -q -r -o stricthostkeychecking=no $VM_KEY $GEODE_ADDON_WORKSPACES_HOME/initenv.sh $VM_USER@$VM_HOST:$VM_GEODE_ADDON_WORKSPACES_HOME/
    fi
-   if [ "$ADDONENV_EXISTS" != "true" ]; then
+   if [[ "$ADDONENV_EXISTS" == *"false" ]]; then
       sed -e 's|export GEODE_ADDON_WORKSPACES_HOME=.*$|export GEODE_ADDON_WORKSPACES_HOME='\"$VM_GEODE_ADDON_WORKSPACES_HOME\"'|' \
           $GEODE_ADDON_WORKSPACES_HOME/.addonenv.sh > /tmp/.addonenv.sh
-      scp -q -r -o stricthostkeychecking=no $VM_KEY /tmp/.addonenv.sh $VM_USER@$VM_HOST:$VM_GEODE_ADDON_WORKSPACES_HOME/
+      if [ "$SIMULATE" == "true" ]; then
+         echo scp -q -r -o stricthostkeychecking=no $VM_KEY /tmp/.addonenv.sh $VM_USER@$VM_HOST:$VM_GEODE_ADDON_WORKSPACES_HOME/
+      else
+         scp -q -r -o stricthostkeychecking=no $VM_KEY /tmp/.addonenv.sh $VM_USER@$VM_HOST:$VM_GEODE_ADDON_WORKSPACES_HOME/
+      fi
    fi
-   if [ "$SETENV_EXISTS" != "true" ]; then
-      scp -q -r -o stricthostkeychecking=no $VM_KEY /tmp/workspaces_setenv.sh $VM_USER@$VM_HOST:$VM_GEODE_ADDON_WORKSPACES_HOME/setenv.sh
+   if [[ "$SETENV_EXISTS" == "false" ]]; then
+      if [ "$SIMULATE" == "true" ]; then
+         echo scp -q -r -o stricthostkeychecking=no $VM_KEY /tmp/workspaces_setenv.sh $VM_USER@$VM_HOST:$VM_GEODE_ADDON_WORKSPACES_HOME/setenv.sh
+      else
+         scp -q -r -o stricthostkeychecking=no $VM_KEY /tmp/workspaces_setenv.sh $VM_USER@$VM_HOST:$VM_GEODE_ADDON_WORKSPACES_HOME/setenv.sh
+      fi
    fi
 done
 
@@ -204,10 +291,10 @@ GEODE_HOME_NOT_FOUND_LIST=""
 for VM_HOST in $__VM_HOSTS; do
    JAVA_HOME_EXISTS=$(ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "$JAVA_HOME_COMMAND")
    GEODE_HOME_EXISTS=$(ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "$GEODE_HOME_COMMAND")
-   if [ "$JAVA_HOME_EXISTS" == "false" ]; then
+   if [[ "$JAVA_HOME_EXISTS" == *"false" ]]; then
       JAVA_HOME_NOT_FOUND_LIST="$JAVA_HOME_NOT_FOUND_LIST $VM_HOST"
    fi
-   if [ "$GEODE_HOME_EXISTS" == "false" ]; then
+   if [[ "$GEODE_HOME_EXISTS" == *"false" ]]; then
       GEODE_HOME_NOT_FOUND_LIST="$GEODE_HOME_NOT_FOUND_LIST $VM_HOST"
    fi
 done
@@ -244,3 +331,6 @@ fi
 
 echo -e "${CLightGreen}Workspace sync complete.${CNone}"
 echo ""
+if [ "$SIMULATE" == "true" ]; then
+   echo "Simulation complete."
+fi
diff --git a/geode-addon-deployment/src/main/resources/bin_sh/vm_test b/geode-addon-deployment/src/main/resources/bin_sh/vm_test
--- a/geode-addon-deployment/src/main/resources/bin_sh/vm_test
+++ b/geode-addon-deployment/src/main/resources/bin_sh/vm_test
@@ -7,7 +7,7 @@ EXECUTABLE="`basename $0`"
 
 __options()
 {
-   echo "-vm -?"
+   echo "-cluster -vm -?"
 }
 
 if [ "$OPTIONS" == "true" ]; then
@@ -33,23 +33,30 @@ NAME
    $EXECUTABLE - Test the VM workspace configurations
 
 SYNOPSIS
-   $EXECUTABLE [-vm comma_separated_hosts] [-?]
+   $EXECUTABLE [-cluster cluster_name] [-vm comma_separated_hosts] [-?]
 
 DESCRIPTION
-   Tests the current workspace's VM configurations. It reports each VM's configuration
-   software component status. The generated report should aids you in troubleshooting 
-   any VM-related issues before executing the 'vm_sync' command to synchronise your
-   workspace environment. The VM workspace is configured in the workspace 'setenv.sh'
-   file.
+   Tests workspace configurations of all the VMs defined by the VM_HOSTS environment
+   variable in the workspace 'setenv.sh' file. To test the cluster VMs, specify the
+   cluster with the '-cluster' option. To test a select list of VMs, specify the VM
+   list with the '-vm' option.
 
-   $GEODE_ADDON_WORKSPACE/setenv.sh
+   It reports each VM's configuration status for troubleshooting any VM-related issues
+   before executing the 'vm_sync' command to synchronize the workspace environment.
+
+   Note that this command and all other commands that begin with the "vm_" preprefix are
+   available only on VM workspaces.
+
+   The '-vm' option overrides both the '-cluster' option and VM_HOSTS. The '-cluster' option
+   overrides VM_HOSTS. 
 
 OPTIONS
+   -cluster cluster_name
+             Cluster name.
 
-    -vm comma_separated_hosts
-              A list of VM hosts or addresses separated by comma. Spaces NOT allowed.
-              If this option overrides the workspace's VM_HOSTS set in the 'setenv.sh'
-              file.
+   -vm comma_separated_hosts
+             A comma separated list of VM hosts or addresses. Spaces NOT allowed.
+             This option overrides the workspace's VM_HOSTS set in the 'setenv.sh' file.
 
 EOF
 if [ "$MAN_SPECIFIED" == "false" ]; then
@@ -66,12 +73,60 @@ EOF
    exit
 fi
 
-WORKSPACE_NAME=$(basename "$GEODE_ADDON_WORKSPACE")
-
+# Available only on VM workspaces
 if [ "$VM_ENABLED" != "true" ]; then
-   echo >&2 "ERROR: The cuurent workspace is not VM enabled [$WORKSPACE_NAME]. Command aborted."
-   exit 1
+   echo "----------------------------------------------------------------"
+   echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+   echo "    ERROR: The workspace is not a VM workspace. Command aborted."
+   echo "----------------------------------------------------------------"
+   exit 1 
 fi
+
+# If the -vm option is specified then it overrides all other options
+if [ "$VM_SPECIFIED" == "true" ]; then
+   if [ "$VM_HOSTS_ARG" != "" ] && [[ "$VM_HOSTS_ARG" != *"-"* ]]; then
+      VM_HOSTS=$VM_HOSTS_ARG
+   else
+      echo "----------------------------------------------------------------"
+      echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+      echo >&2 "ERROR: Invalid value for -vm [$VM_HOSTS_ARG]. Command aborted."
+      echo "----------------------------------------------------------------"
+      exit 1
+   fi
+else
+   # The -cluster option overrides VM_HOSTS
+   if [ "$CLUSTER_SPECIFIED" == "true" ]; then
+      if [ "`isClusterExist "$CLUSTER"`" == "false" ]; then 
+         echo "----------------------------------------------------------------"
+         echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+         echo >&2 "ERROR: Cluster does not exist [$CLUSTER]. Command aborted."
+         echo "----------------------------------------------------------------"
+         exit 1
+      fi
+      VM_ENABLED=`getClusterProperty "vm.enabled" "false"`
+      if [ "$VM_ENABLED" == "false" ]; then
+         echo "----------------------------------------------------------------"
+         echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+         echo >&2 "ERROR: Not a VM cluster [$CLUSTER]. To enable VMs, set the 'vm.enabled' property"
+         echo >&2 "       in the 'etc/cluster.properties' file."
+         echo "----------------------------------------------------------------"
+         exit 1
+      fi
+      VM_HOSTS=`getClusterProperty "vm.hosts"`
+      if [ "$VM_HOSTS" == "" ]; then
+         if [ "$VM_HOSTS" == "" ]; then
+            echo "----------------------------------------------------------------"
+            echo "WORKSPACE: $GEODE_ADDON_WORKSPACE"
+            echo >&2 "    ERROR: The 'vm.hosts' property is not set in the 'etc/cluster.properties' file."
+            echo >&2 "           file. Command aborted."
+            echo "----------------------------------------------------------------"
+            exit 1
+         fi
+      fi
+   fi
+fi
+
+WORKSPACE_NAME=$(basename "$GEODE_ADDON_WORKSPACE")
 
 # Replace , with space
 __VM_HOSTS=$(echo "$VM_HOSTS" | sed "s/,/ /g")
@@ -100,6 +155,17 @@ if [ "$KEY" != "" ]; then
    fi
    VM_KEY="-i $KEY"
 fi
+
+# Fail fast: Exit if any of the hosts is not reachable
+for VM_HOST in $__VM_HOSTS; do
+   REPLY=$(ssh -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no -o PasswordAuthentication=no "echo hello" 2>&1)
+   EXIT_CODE=$?
+   if [ "$EXIT_CODE" != "0" ]; then
+      echo -e "ERROR: $VM_HOST - ${CLightRed}Failed${CNone} ($REPLY)"
+      echo "       Command aborted."
+      exit 1
+   fi
+done
 
 if [ "$VM_ENABLED" == "true" ]; then
    ISSUES_FOUND="false"
@@ -155,15 +221,15 @@ for VM_HOST in $__VM_HOSTS; do
    ADDON_EXISTS=$(ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "$ADDON_COMMAND")
    JAVA_HOME_EXISTS=$(ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "$JAVA_HOME_COMMAND")
    GEODE_HOME_EXISTS=$(ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "$GEODE_HOME_COMMAND")
-   if [ "$ADDON_EXISTS" == "false" ]; then
+   if [[ "$ADDON_EXISTS" == *"false" ]]; then
       ADDON_NOT_FOUND_LIST="$ADDON_NOT_FOUND_LIST $VM_HOST"
    fi
-   if [ "$JAVA_HOME_EXISTS" == "false" ]; then
+   if [[ "$JAVA_HOME_EXISTS" == *"false" ]]; then
       JAVA_HOME_NOT_FOUND_LIST="$JAVA_HOME_NOT_FOUND_LIST $VM_HOST"
       ISSUES_FOUND="true"
       SOFTWARE_ISSUES_FOUND="true"
    fi
-   if [ "$GEODE_HOME_EXISTS" == "false" ]; then
+   if [[ "$GEODE_HOME_EXISTS" == *"false" ]]; then
       GEODE_HOME_NOT_FOUND_LIST="$GEODE_HOME_NOT_FOUND_LIST $VM_HOST"
       ISSUES_FOUND="true"
       SOFTWARE_ISSUES_FOUND="true"
@@ -206,13 +272,14 @@ if [ "$ADDON_NOT_FOUND_LIST" != "" ]; then
    echo "$VM_GEODE_ADDON_HOME"
    echo "   geode-addon is not installed on the following VMs. It will be automatically installed"
    echo "   when you execute 'vm_sync'."
-   echo "      $JAVA_HOME_NOT_FOUND_LIST"
+   echo "      $ADDON_NOT_FOUND_LIST"
    echo "------------------------------------------------------------------------------------------"
 fi
 
 # Display cluster info
+if [ "$CLUSTER_SPECIFIED" == "true" ]; then
 __VM_ENABLED=`getClusterProperty "vm.enabled" "false"`
-__VM_HOSTS=`getClusterProperty "vm.hosts"`
+__VM_HOSTS_CLUSTER=`getClusterProperty "vm.hosts"`
 __VM_USER=`getClusterProperty "vm.user" "$DEFAULT_USER"`
 __VM_PRIVATE_KEY_FILE=`getClusterProperty "vm.privateKeyFile"`
 cat <<EOF
@@ -224,7 +291,7 @@ Cluster Properties File:
 
 Environment:
           vm.enabled=$__VM_ENABLED
-            vm.hosts=$__VM_HOSTS
+            vm.hosts=$__VM_HOSTS_CLUSTER
              vm.user=$__VM_USER
    vm.privateKeyFile=$__VM_PRIVATE_KEY_FILE
 
@@ -252,9 +319,25 @@ if [ "$__VM_ENABLED" == "$VM_ENABLED" ] &&
    [ "$__VM_HOSTS" == "$VM_HOSTS" ] &&
    [ "$__VM_USER" == "$VM_USER" ] &&
    [ "$__VM_PRIVATE_KEY_FILE" == "$__VM_PRIVATE_KEY_FILE" ]; then
-   echo "The cluster VM environment is identical to the workspace VM environment."
+   echo "The cluster VM environment setup is identical to the workspace VM environment setup."
+fi
+
+# Check if the cluster has been deployed
+CLUSTER_NOT_FOUND_LIST=""
+# Replace , with space
+__VM_HOSTS=$(echo "$__VM_HOSTS_CLUSTER" | sed "s/,/ /g")
+if [ "$NETWORK_ISSUES_VM_HOSTS" == "" ]; then
+   CLUSTER_COMMAND="if [ -d "$VM_GEODE_ADDON_WORKSPACE/clusters/$CLUSTER" ]; then echo true; else echo false; fi"
+   for VM_HOST in $__VM_HOSTS; do
+      CLUSTER_EXISTS=$(ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "$CLUSTER_COMMAND")
+      if [[ "$CLUSTER_EXISTS" == *"false" ]]; then
+	 CLUSTER_NOT_FOUND_LIST="$CLUSTER_NOT_FOUND_LIST $VM_HOST"
+	 CLUSTER_ISSUES_FOUND=true
+      fi
+   done
 fi
 echo "------------------------------------------------------------------------------------------"
+fi
 
 # Summary
 echo "------------------------------------------------------------------------------------------"
@@ -291,13 +374,20 @@ else
       echo "     $GEODE_HOME_NOT_FOUND_LIST"
    fi
 fi
+if [ "$CLUSTER_SPECIFIED" == "true" ]; then
 echo "Cluster Issues: "
 if [ "$CLUSTER_ISSUES_FOUND" == "true" ]; then
-   echo "   The cluster VM environment is different from the workspace VM environment. This might" 
-   echo "   not be an error as cluster settings are typically a subset of the workspace settings."
-   echo "   Please verify."
+   if [ "$CLUSTER_NOT_FOUND_LIST" != "" ]; then
+      echo "   The following VM hosts do not have the '$CLUSTER' cluster deployed."
+      echo -e "     ${CLightRed}$CLUSTER_NOT_FOUND_LIST${CNone}"
+   else
+      echo "   The cluster VM environment is different from the workspace VM environment. This might" 
+      echo "   not be an error as cluster settings are typically a subset of the workspace settings."
+      echo "   Please verify."
+   fi
 else
    echo -e "   ${CLightGreen}None.${CNone}"
+fi
 fi
 echo "------------------------------------------------------------------------------------------"
 
